In [ ]:
# Add yaml files  
from pathlib import Path

root = Path(
    "/home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold"
)

for fold in range(1, 6):

    yaml_content = f"""
path: {root}/fold{fold}

train: train/images
val: val/images

nc: 4

names:
  0: breast cancer g1
  1: breast cancer g2
  2: breast cancer g3
  3: breast normalcell
"""

    with open(root / f"fold{fold}.yaml", "w") as f:
        f.write(yaml_content.strip())

print("Created fold1.yaml ... fold5.yaml")

Created fold1.yaml ... fold5.yaml

In [1]:
from ultralytics import YOLO
import pandas as pd
from pathlib import Path

ROOT = Path(
    "/home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold"
)

results = []

for fold in range(1, 6):

    print(f"\n========== FOLD {fold} ==========\n")

    yaml_file = ROOT / f"fold{fold}.yaml"

    # -------------------------------------------------
    # CHANGE THIS TO YOUR MODEL
    # -------------------------------------------------

    model = YOLO("yolov8n.pt")

    model.train(
        data=str(yaml_file),
        epochs=100,
        imgsz=512,
        batch=4,
        name=f"fold{fold}",
        project="5fold_runs"
    )

    csv_path = (
        Path("5fold_runs")
        / f"fold{fold}"
        / "results.csv"
    )

    df = pd.read_csv(csv_path)

    best_idx = df["metrics/mAP50-95(B)"].idxmax()

    best = df.loc[best_idx]

    precision = best["metrics/precision(B)"]
    recall = best["metrics/recall(B)"]

    f1 = (
        2 * precision * recall
        / (precision + recall + 1e-9)
    )

    results.append({
        "Fold": fold,
        "Epoch": int(best["epoch"]),
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "mAP50": best["metrics/mAP50(B)"],
        "mAP50_95": best["metrics/mAP50-95(B)"]
    })

summary = pd.DataFrame(results)

summary.to_csv(
    "5fold_results.csv",
    index=False
)

print("\nSaved 5fold_results.csv")

========== FOLD 1 ==========

New https://pypi.org/project/ultralytics/8.4.61 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.165 🚀 Python-3.10.12 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold/fold1.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=fold12, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=5fold_runs, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=5fold_runs/fold12, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752092  ultralytics.nn.modules.head.Detect           [4, [64, 128, 256]]
Model summary: 129 layers, 3,011,628 parameters, 3,011,612 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...

KeyboardInterrupt:

In [1]:
from ultralytics import YOLO
import pandas as pd
from pathlib import Path

In [2]:
FOLD = 5

In [3]:
ROOT = Path(
    "/home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold"
)

yaml_file = ROOT / f"fold{FOLD}.yaml"

model = YOLO("yolov8n.pt")

model.train(
    data=str(yaml_file),
    epochs=100,
    imgsz=512,
    batch=4,
    project="5fold_runs",
    name=f"fold{FOLD}",
    exist_ok=True
)

New https://pypi.org/project/ultralytics/8.4.61 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.165 🚀 Python-3.10.12 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold/fold5.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=fold5, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=5fold_runs, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=5fold_runs/fold5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752092  ultralytics.nn.modules.head.Detect           [4, [64, 128, 256]]
Model summary: 129 layers, 3,011,628 parameters, 3,011,612 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 115.4±26.2 MB/s, size: 59.1 KB)

train: Scanning /home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold/fold5/train/labels... 522 images, 0 backgrounds, 0 corrupt: 100%|██████████| 522/522 [00:00<00:00, 1174.56it/s]

train: New cache created: /home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold/fold5/train/labels.cache

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 114.4±36.2 MB/s, size: 55.4 KB)

val: Scanning /home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold/fold5/val/labels... 130 images, 0 backgrounds, 0 corrupt: 100%|██████████| 130/130 [00:00<00:00, 709.87it/s]

val: New cache created: /home/zaman/Code/Breast_Cancer_Detection_and_Monitoring/Cancer.v1i.yolov8/5-fold/fold5/val/labels.cache

Plotting labels to 5fold_runs/fold5/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 512 train, 512 val
Using 8 dataloader workers
Logging results to 5fold_runs/fold5
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/100     0.391G       1.07      2.494      1.544          3        512: 100%|██████████| 131/131 [00:12<00:00, 10.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.30it/s]

                   all        130        130      0.298      0.755      0.546      0.421

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/100     0.408G     0.7295      1.494      1.177          7        512: 100%|██████████| 131/131 [00:14<00:00,  9.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  9.99it/s]

                   all        130        130      0.418      0.886      0.542      0.452

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/100     0.426G     0.7016       1.37      1.154          5        512: 100%|██████████| 131/131 [00:12<00:00, 10.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 10.03it/s]

                   all        130        130      0.518      0.663      0.555      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/100     0.443G     0.6334      1.271       1.08          7        512: 100%|██████████| 131/131 [00:12<00:00, 10.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.61it/s]

                   all        130        130      0.434      0.903      0.682      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/100     0.459G     0.5945       1.16      1.084          3        512: 100%|██████████| 131/131 [00:10<00:00, 12.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 12.07it/s]

                   all        130        130      0.453      0.887      0.674      0.604

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/100     0.496G     0.5925      1.108      1.065          6        512: 100%|██████████| 131/131 [00:12<00:00, 10.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.63it/s]

                   all        130        130      0.576      0.911      0.684      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/100     0.514G      0.582      1.096      1.062          4        512: 100%|██████████| 131/131 [00:11<00:00, 11.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 11.31it/s]

                   all        130        130      0.391       0.75      0.635       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/100     0.531G     0.5321     0.9689      1.039          5        512: 100%|██████████| 131/131 [00:10<00:00, 12.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.46it/s]

                   all        130        130      0.541      0.942      0.741       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/100     0.547G     0.5451     0.9244      1.043          8        512: 100%|██████████| 131/131 [00:11<00:00, 11.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.69it/s]

                   all        130        130      0.622      0.895      0.733       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/100     0.564G     0.5108     0.9205      1.033          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.52it/s]

                   all        130        130       0.58      0.947      0.726      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/100     0.582G     0.5335     0.8812       1.04          8        512: 100%|██████████| 131/131 [00:10<00:00, 12.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.53it/s]

                   all        130        130      0.544      0.875       0.67      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/100     0.598G     0.5386     0.8921      1.055          3        512: 100%|██████████| 131/131 [00:10<00:00, 12.35it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.92it/s]

                   all        130        130      0.613       0.87      0.796      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/100     0.615G     0.5278     0.8613      1.046          2        512: 100%|██████████| 131/131 [00:10<00:00, 12.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.17it/s]

                   all        130        130      0.572      0.911      0.724      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/100     0.633G     0.4959     0.8339      1.028          6        512: 100%|██████████| 131/131 [00:11<00:00, 11.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.85it/s]

                   all        130        130      0.595       0.92      0.725      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/100      0.65G     0.4956     0.8296      1.019          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.20it/s]

                   all        130        130      0.615      0.943      0.724      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/100     0.666G     0.5204     0.8143      1.035          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.31it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.71it/s]

                   all        130        130      0.673      0.844      0.764      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/100     0.684G     0.4868     0.8417      1.019          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.96it/s]

                   all        130        130       0.61      0.899      0.756      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/100     0.701G     0.4785     0.7866      1.015          5        512: 100%|██████████| 131/131 [00:11<00:00, 11.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.20it/s]

                   all        130        130      0.607      0.892      0.741      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/100     0.717G     0.4833     0.7774      1.011          5        512: 100%|██████████| 131/131 [00:10<00:00, 12.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.39it/s]

                   all        130        130      0.555      0.927      0.763      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/100     0.734G     0.4561     0.7445      1.004          5        512: 100%|██████████| 131/131 [00:10<00:00, 12.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.19it/s]

                   all        130        130      0.722      0.796      0.774      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/100     0.752G     0.4474     0.7317          1          7        512: 100%|██████████| 131/131 [00:11<00:00, 11.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.66it/s]

                   all        130        130      0.612       0.88       0.72      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/100      0.77G     0.4791     0.7384      1.017          6        512: 100%|██████████| 131/131 [00:11<00:00, 11.35it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  7.97it/s]

                   all        130        130      0.537      0.828      0.712      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/100     0.787G     0.4628     0.7385     0.9979          7        512: 100%|██████████| 131/131 [00:15<00:00,  8.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  7.98it/s]

                   all        130        130      0.697       0.86      0.802      0.733

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/100     0.803G     0.4237     0.6654     0.9914          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 12.15it/s]

                   all        130        130      0.677      0.859      0.824       0.73

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/100      0.82G     0.4535      0.674     0.9938          5        512: 100%|██████████| 131/131 [00:13<00:00,  9.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 10.41it/s]

                   all        130        130      0.693      0.784      0.806      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/100     0.838G     0.4494      0.702      1.003          6        512: 100%|██████████| 131/131 [00:12<00:00, 10.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.09it/s]

                   all        130        130       0.59      0.892      0.786      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/100     0.854G     0.4027      0.664     0.9713          8        512: 100%|██████████| 131/131 [00:13<00:00,  9.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  8.38it/s]

                   all        130        130      0.688      0.898      0.777      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/100     0.871G      0.447     0.7061     0.9967          5        512: 100%|██████████| 131/131 [00:13<00:00,  9.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  8.08it/s]

                   all        130        130      0.734       0.87      0.821      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/100     0.889G     0.4361     0.6878     0.9921          8        512: 100%|██████████| 131/131 [00:15<00:00,  8.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 11.35it/s]

                   all        130        130      0.654       0.82      0.775      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/100     0.906G     0.4069     0.6839     0.9773          6        512: 100%|██████████| 131/131 [00:12<00:00, 10.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  9.69it/s]

                   all        130        130      0.654      0.802      0.779      0.714

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/100     0.922G     0.4318     0.6902     0.9973          6        512: 100%|██████████| 131/131 [00:13<00:00,  9.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 10.87it/s]

                   all        130        130      0.789      0.797       0.83      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/100     0.939G     0.3911     0.6272      0.963          5        512: 100%|██████████| 131/131 [00:15<00:00,  8.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  8.32it/s]

                   all        130        130      0.637      0.892      0.812      0.739

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/100     0.957G     0.4025     0.6263     0.9824          4        512: 100%|██████████| 131/131 [00:14<00:00,  8.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 10.28it/s]

                   all        130        130      0.785      0.758      0.798      0.737

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/100     0.975G     0.3826     0.6421     0.9748          6        512: 100%|██████████| 131/131 [00:11<00:00, 11.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.17it/s]

                   all        130        130       0.63      0.893      0.789      0.728

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/100      0.99G     0.3961     0.6445     0.9713          3        512: 100%|██████████| 131/131 [00:10<00:00, 12.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.66it/s]

                   all        130        130      0.787      0.752      0.821      0.764

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/100      1.01G     0.3942     0.6226     0.9863          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.31it/s]

                   all        130        130      0.686      0.705      0.738      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/100      1.03G     0.3903     0.6288      0.977          5        512: 100%|██████████| 131/131 [00:11<00:00, 11.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.67it/s]

                   all        130        130      0.696       0.87      0.855      0.792

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/100      1.04G     0.3735     0.6201     0.9661          3        512: 100%|██████████| 131/131 [00:10<00:00, 11.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.99it/s]

                   all        130        130      0.791      0.813      0.875      0.819

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/100      1.06G     0.3797     0.6044     0.9692          7        512: 100%|██████████| 131/131 [00:11<00:00, 11.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.05it/s]

                   all        130        130        0.7      0.819      0.825      0.768

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/100      1.08G     0.3813      0.598     0.9743          8        512: 100%|██████████| 131/131 [00:11<00:00, 11.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.11it/s]

                   all        130        130      0.727      0.791      0.829       0.77

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/100      1.09G     0.3794     0.5903     0.9783          5        512: 100%|██████████| 131/131 [00:11<00:00, 11.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.21it/s]

                   all        130        130      0.722       0.86      0.845      0.784

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/100      1.11G     0.3586     0.5852     0.9744          5        512: 100%|██████████| 131/131 [00:11<00:00, 11.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.93it/s]

                   all        130        130      0.665      0.847      0.849      0.789

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/100      1.13G     0.3523     0.5626     0.9577          4        512: 100%|██████████| 131/131 [00:13<00:00,  9.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.70it/s]

                   all        130        130      0.633      0.901      0.826      0.779

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/100      1.14G     0.3862     0.5917     0.9934          3        512: 100%|██████████| 131/131 [00:14<00:00,  9.30it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.89it/s]

                   all        130        130      0.644      0.898       0.85      0.788

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/100      1.16G     0.3704     0.6031      0.968          5        512: 100%|██████████| 131/131 [00:13<00:00,  9.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.57it/s]

                   all        130        130      0.746      0.811      0.825      0.777

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/100      1.18G     0.3511      0.562     0.9543          7        512: 100%|██████████| 131/131 [00:11<00:00, 11.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.46it/s]

                   all        130        130      0.799      0.797       0.88      0.817

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/100       1.2G     0.3321     0.5307     0.9536          6        512: 100%|██████████| 131/131 [00:13<00:00,  9.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.69it/s]

                   all        130        130      0.813      0.851      0.851      0.805

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/100      1.21G     0.3383     0.5188     0.9582          5        512: 100%|██████████| 131/131 [00:14<00:00,  8.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 10.23it/s]

                   all        130        130      0.761      0.816      0.863      0.808

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/100      1.23G     0.3634     0.5568     0.9677          3        512: 100%|██████████| 131/131 [00:14<00:00,  9.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  8.60it/s]

                   all        130        130       0.76      0.899      0.906      0.837

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/100      1.25G     0.3505     0.5357     0.9477          4        512: 100%|██████████| 131/131 [00:15<00:00,  8.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  8.41it/s]

                   all        130        130      0.852      0.816      0.908      0.839

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/100      1.26G     0.3558     0.5634     0.9657          4        512: 100%|██████████| 131/131 [00:13<00:00,  9.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.39it/s]

                   all        130        130      0.848      0.826      0.906      0.848

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/100      1.28G     0.3282     0.5347     0.9546          6        512: 100%|██████████| 131/131 [00:11<00:00, 11.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.34it/s]

                   all        130        130      0.844      0.823      0.926      0.865

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/100       1.3G     0.3292     0.5488     0.9433          8        512: 100%|██████████| 131/131 [00:10<00:00, 12.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.74it/s]

                   all        130        130      0.852      0.875      0.922      0.865

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/100      1.31G     0.3327     0.5255     0.9503          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.64it/s]

                   all        130        130      0.805       0.88      0.911      0.842

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/100      1.33G     0.3242     0.5156     0.9408          7        512: 100%|██████████| 131/131 [00:10<00:00, 12.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.94it/s]

                   all        130        130      0.826      0.855      0.898      0.844

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/100      1.35G     0.3322     0.5167     0.9471          4        512: 100%|██████████| 131/131 [00:10<00:00, 11.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.44it/s]

                   all        130        130      0.771      0.882      0.931      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/100      1.37G     0.3179     0.4973     0.9446          4        512: 100%|██████████| 131/131 [00:11<00:00, 11.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.11it/s]

                   all        130        130      0.767      0.938       0.93      0.884

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/100      1.38G      0.305     0.4724     0.9402          5        512: 100%|██████████| 131/131 [00:10<00:00, 11.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.10it/s]

                   all        130        130      0.739      0.951      0.936      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/100       1.4G     0.3162     0.4833     0.9422          7        512: 100%|██████████| 131/131 [00:10<00:00, 12.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.35it/s]

                   all        130        130      0.815      0.866       0.94      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/100      1.42G     0.2992     0.4796     0.9362          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.95it/s]

                   all        130        130      0.909       0.84      0.945      0.876

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/100      1.44G     0.3013     0.4702     0.9411          3        512: 100%|██████████| 131/131 [00:10<00:00, 12.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.60it/s]

                   all        130        130       0.81      0.874      0.934      0.881

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/100      1.45G     0.3093     0.4966     0.9446          6        512: 100%|██████████| 131/131 [00:10<00:00, 12.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.49it/s]

                   all        130        130      0.864      0.865      0.934      0.889

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/100      1.47G      0.299     0.4649     0.9391          5        512: 100%|██████████| 131/131 [00:10<00:00, 11.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.25it/s]

                   all        130        130      0.873      0.892      0.939      0.901

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/100      1.49G     0.2893     0.4735     0.9263          8        512: 100%|██████████| 131/131 [00:11<00:00, 11.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.04it/s]

                   all        130        130       0.85      0.943      0.963      0.916

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/100       1.5G     0.2886     0.4393     0.9378          3        512: 100%|██████████| 131/131 [00:11<00:00, 11.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.03it/s]

                   all        130        130      0.787      0.962      0.929      0.888

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/100      1.52G     0.2974     0.4548      0.939          3        512: 100%|██████████| 131/131 [00:11<00:00, 11.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  9.33it/s]

                   all        130        130      0.792      0.919      0.942      0.897

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/100      1.54G     0.2913     0.4539     0.9268          4        512: 100%|██████████| 131/131 [00:11<00:00, 11.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.93it/s]

                   all        130        130      0.848       0.93      0.942      0.861

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/100      1.55G     0.2873     0.4278     0.9299          8        512: 100%|██████████| 131/131 [00:15<00:00,  8.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 12.41it/s]

                   all        130        130      0.861      0.912      0.942      0.907

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/100      1.57G     0.2903     0.4599     0.9306          6        512: 100%|██████████| 131/131 [00:11<00:00, 11.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.15it/s]

                   all        130        130      0.917      0.926      0.959      0.919

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/100      1.59G     0.2643     0.4146     0.9135          8        512: 100%|██████████| 131/131 [00:12<00:00, 10.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 12.33it/s]

                   all        130        130      0.888      0.861      0.953      0.922

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/100      1.61G     0.2824     0.4359     0.9348          3        512: 100%|██████████| 131/131 [00:11<00:00, 11.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 12.57it/s]

                   all        130        130      0.893      0.939      0.962      0.921

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/100      1.62G     0.2693     0.4072     0.9199          2        512: 100%|██████████| 131/131 [00:11<00:00, 11.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.81it/s]

                   all        130        130      0.927      0.933      0.973      0.932

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/100      1.64G       0.27     0.3897     0.9294          4        512: 100%|██████████| 131/131 [00:11<00:00, 11.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.76it/s]

                   all        130        130      0.904      0.917      0.963      0.932

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/100      1.66G     0.2701     0.4265     0.9221          5        512: 100%|██████████| 131/131 [00:10<00:00, 12.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.91it/s]

                   all        130        130      0.897      0.923      0.959      0.925

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/100      1.67G     0.2727      0.399     0.9205          3        512: 100%|██████████| 131/131 [00:10<00:00, 11.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.33it/s]

                   all        130        130      0.903      0.944      0.969       0.93

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/100      1.69G     0.2619     0.3942     0.9165          6        512: 100%|██████████| 131/131 [00:10<00:00, 11.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.90it/s]

                   all        130        130      0.947      0.878       0.97      0.938

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/100      1.71G     0.2415     0.3567     0.9176          7        512: 100%|██████████| 131/131 [00:11<00:00, 11.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  9.61it/s]

                   all        130        130      0.953      0.965      0.981      0.951

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/100      1.72G     0.2614     0.3804     0.9157          6        512: 100%|██████████| 131/131 [00:14<00:00,  9.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 10.27it/s]

                   all        130        130      0.847      0.935       0.97      0.932

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/100      1.74G     0.2465     0.3652     0.9195          4        512: 100%|██████████| 131/131 [00:12<00:00, 10.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 11.92it/s]

                   all        130        130      0.959      0.921      0.979      0.949

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/100      1.76G     0.2476      0.369     0.9128          4        512: 100%|██████████| 131/131 [00:14<00:00,  9.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  7.80it/s]

                   all        130        130      0.962      0.965      0.987      0.964

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/100      1.78G     0.2434      0.355     0.9102          4        512: 100%|██████████| 131/131 [00:14<00:00,  9.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 11.85it/s]

                   all        130        130      0.942      0.948      0.986      0.955

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/100      1.79G     0.2442     0.3612     0.9267          6        512: 100%|██████████| 131/131 [00:14<00:00,  9.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  8.18it/s]

                   all        130        130      0.954      0.948      0.983       0.96

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/100      1.81G     0.2367     0.3622     0.9102          8        512: 100%|██████████| 131/131 [00:14<00:00,  8.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  8.90it/s]

                   all        130        130      0.923      0.929      0.983      0.952

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/100      1.83G     0.2361     0.3376     0.9022          4        512: 100%|██████████| 131/131 [00:15<00:00,  8.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.61it/s]

                   all        130        130      0.918      0.967      0.982      0.959

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/100      1.84G      0.242     0.3411      0.906          2        512: 100%|██████████| 131/131 [00:14<00:00,  9.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 10.05it/s]

                   all        130        130      0.957      0.935      0.974      0.951

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/100      1.86G     0.2321     0.3346     0.9091          4        512: 100%|██████████| 131/131 [00:14<00:00,  8.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  9.34it/s]

                   all        130        130      0.922      0.957      0.979      0.959

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/100      1.88G     0.2326     0.3479     0.9049          3        512: 100%|██████████| 131/131 [00:15<00:00,  8.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  7.53it/s]

                   all        130        130      0.952      0.929      0.977      0.958

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/100      1.89G     0.2254     0.3437     0.9116          6        512: 100%|██████████| 131/131 [00:12<00:00, 10.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.84it/s]

                   all        130        130      0.973      0.954      0.988      0.963

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/100      1.91G     0.2263     0.3309     0.9015          7        512: 100%|██████████| 131/131 [00:11<00:00, 11.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.45it/s]

                   all        130        130       0.95      0.981      0.987      0.959

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/100      1.93G      0.235     0.3394     0.9177          3        512: 100%|██████████| 131/131 [00:12<00:00, 10.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.21it/s]

                   all        130        130      0.949      0.946      0.982      0.965

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/100      1.95G     0.2215     0.4005     0.9026          2        512: 100%|██████████| 131/131 [00:12<00:00, 10.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 13.77it/s]

                   all        130        130      0.953      0.939      0.983      0.963

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/100      1.96G     0.2137     0.2967     0.9196          2        512: 100%|██████████| 131/131 [00:14<00:00,  9.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  8.68it/s]

                   all        130        130      0.967       0.93       0.98      0.963

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/100      1.98G     0.2172     0.2653     0.9059          2        512: 100%|██████████| 131/131 [00:13<00:00,  9.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.56it/s]

                   all        130        130       0.96      0.961      0.981      0.962

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/100         2G     0.2039     0.2543     0.8924          2        512: 100%|██████████| 131/131 [00:11<00:00, 11.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 14.72it/s]

                   all        130        130      0.961      0.942      0.975      0.957

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/100      2.01G     0.2135     0.2473     0.9016          2        512: 100%|██████████| 131/131 [00:11<00:00, 11.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 11.74it/s]

                   all        130        130      0.963      0.966      0.982      0.968

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/100     0.748G     0.2122     0.2714     0.9031          2        512: 100%|██████████| 131/131 [00:13<00:00,  9.38it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 11.71it/s]

                   all        130        130       0.93      0.981      0.986       0.97

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/100     0.768G     0.2027     0.2251     0.9005          2        512: 100%|██████████| 131/131 [00:13<00:00,  9.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00,  9.43it/s]

                   all        130        130      0.924      0.971      0.986      0.967

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/100     0.768G     0.2057      0.222     0.8941          2        512: 100%|██████████| 131/131 [00:13<00:00,  9.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.40it/s]

                   all        130        130      0.973      0.971      0.983      0.965

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/100     0.768G     0.2023     0.2141     0.9014          2        512: 100%|██████████| 131/131 [00:11<00:00, 10.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.30it/s]

                   all        130        130      0.955      0.962      0.986       0.97

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/100     0.768G     0.1912     0.2247     0.9023          2        512: 100%|██████████| 131/131 [00:12<00:00, 10.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:01<00:00, 15.33it/s]

                   all        130        130      0.952       0.96      0.986      0.968

100 epochs completed in 0.389 hours.
Optimizer stripped from 5fold_runs/fold5/weights/last.pt, 6.2MB
Optimizer stripped from 5fold_runs/fold5/weights/best.pt, 6.2MB

Validating 5fold_runs/fold5/weights/best.pt...
Ultralytics 8.3.165 🚀 Python-3.10.12 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
Model summary (fused): 72 layers, 3,006,428 parameters, 0 gradients, 8.1 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 17/17 [00:02<00:00,  6.02it/s]

                   all        130        130      0.955      0.961      0.986       0.97
      breast cancer g1         22         22      0.951      0.887      0.972      0.949
      breast cancer g2         32         32      0.968      0.958      0.988      0.969
      breast cancer g3         28         28       0.91          1       0.99      0.966
     breast normalcell         48         48      0.992          1      0.995      0.995
Speed: 0.3ms preprocess, 13.8ms inference, 0.0ms loss, 2.5ms postprocess per image
Results saved to 5fold_runs/fold5

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7e3578e50d30>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.75862,     0.75862,           0],
       [          1,           1,           1, ...,     0.82051,     0.82051,           0],
       [          1,           1,           1, ...,     0.96552,     0.96552,           0],
       [          1,           1,           1, ...,           1,           1,           0]]), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,

In [4]:
import pandas as pd
from pathlib import Path

csv_path = Path(f"5fold_runs/fold{FOLD}/results.csv")

df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip()

best_idx = df["metrics/mAP50-95(B)"].idxmax()

best = df.loc[best_idx]

precision = best["metrics/precision(B)"]
recall = best["metrics/recall(B)"]

f1 = 2 * precision * recall / (precision + recall + 1e-9)

result = pd.DataFrame([{
    "Fold": FOLD,
    "Best Epoch": int(best["epoch"]),
    "Precision": precision,
    "Recall": recall,
    "F1": f1,
    "mAP50": best["metrics/mAP50(B)"],
    "mAP50-95": best["metrics/mAP50-95(B)"]
}])

result

   Fold  Best Epoch  Precision   Recall        F1    mAP50  mAP50-95
0     5          99    0.95546  0.96169  0.958565  0.98631   0.97001

In [5]:
result.to_csv(
    f"fold_{FOLD}_summary.csv",
    index=False
)

print(f"Saved fold_{FOLD}_summary.csv")

Saved fold_5_summary.csv

In [6]:
#Run only after all the folds are completed
import pandas as pd

files = [
    "fold_1_summary.csv",
    "fold_2_summary.csv",
    "fold_3_summary.csv",
    "fold_4_summary.csv",
    "fold_5_summary.csv"
]

dfs = [pd.read_csv(f) for f in files]

all_folds = pd.concat(dfs, ignore_index=True)

all_folds

   Fold  Best Epoch  Precision   Recall        F1    mAP50  mAP50-95
0     1           2    0.41268  0.89640  0.565170  0.58038   0.50512
1     2          89    0.95522  0.95733  0.956274  0.97938   0.94198
2     3          90    0.91762  0.94671  0.931938  0.97530   0.94218
3     4          90    0.96484  0.96946  0.967144  0.98964   0.95569
4     5          99    0.95546  0.96169  0.958565  0.98631   0.97001

In [7]:
metrics = [
    "Precision",
    "Recall",
    "F1",
    "mAP50",
    "mAP50-95"
]

summary = []

for metric in metrics:

    summary.append({
        "Metric": metric,
        "Mean": all_folds[metric].mean(),
        "Std": all_folds[metric].std(),
        "Mean ± Std":
            f"{all_folds[metric].mean():.4f} ± "
            f"{all_folds[metric].std():.4f}"
    })

summary_df = pd.DataFrame(summary)

summary_df

      Metric      Mean       Std       Mean ± Std
0  Precision  0.841164  0.240215  0.8412 ± 0.2402
1     Recall  0.946318  0.029091  0.9463 ± 0.0291
2         F1  0.875818  0.174150  0.8758 ± 0.1741
3      mAP50  0.902202  0.179992  0.9022 ± 0.1800
4   mAP50-95  0.862996  0.200392  0.8630 ± 0.2004

In [8]:
paper_table = summary_df[["Metric", "Mean ± Std"]]

paper_table

      Metric       Mean ± Std
0  Precision  0.8412 ± 0.2402
1     Recall  0.9463 ± 0.0291
2         F1  0.8758 ± 0.1741
3      mAP50  0.9022 ± 0.1800
4   mAP50-95  0.8630 ± 0.2004

In [ ]:
import matplotlib.pyplot as plt

metrics = [
    "Precision",
    "Recall",
    "F1",
    "mAP50",
    "mAP50-95"
]

ax = all_folds.set_index("Fold")[metrics].plot(
    kind="bar",
    figsize=(12,6)
)

plt.title("5-Fold Cross Validation Results")
plt.ylabel("Score")
plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

plt.savefig(
    "5fold_comparison.png",
    dpi=300
)

plt.show()

: